#startfluxbox
#tint2 &
#pekwm
#wintc-taskband &
exec   setxkbmap -layout us,ru -option "grp:alt_shift_toggle,grp_led:scroll" -variant ",winkeys"  &  
alacritty -e screen_check.sh &
pcmanfm --desktop &
startxfce4
