#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/xfce/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
pcmanfm &
wintc-taskband &
feh --bg-scale /usr/local/share/backgrounds/wintc/bliss.jpg
setxkbmap -layout us,ru -option "grp:alt_shift_toggle,grp_led:scroll" -variant ",winkeys"  &
firefox-dev &
alacritty -e screen_check.sh &
exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/xfce/.fluxbox/log"
